export const LOADING = 'LOADING';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const GET_COOKIE_USER_VALUES = 'GET_COOKIE_USER_VALUES';
export const DELETE_COOKIE_USER_VALUES = 'DELETE_COOKIE_USER_VALUES';


