apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: muhammedfayiscc/s-cart-auth
          ports:
            - containerPort: 50051
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongo-svc:27017/auth
            - name: KAFKA_CLIENT_ID
              value: "auth-service-consumer-1" # You can use unique identifiers per replica if needed
            - name: KAFKA_BROKERS
              value: "kafka-depl-0.kafka-headless.default.svc.cluster.local:9092"
            - name: GROUP_ID
              value: "auth-service-group"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
#infra/k8s/auth-svc.yml

apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: auth
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: grpc
