apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: muhammedfayiscc/s-cart-orders
          env:
            - name: MONGO_URI
              value: mongodb://orders-mongo-svc:27017/orders?replicaSet=rs0
            - name: KAFKA_CLIENT_ID
              value: "order-service-consumer-1" # You can use unique identifiers per replica if needed
            - name: KAFKA_BROKERS
              value: "kafka-depl-0.kafka-headless.default.svc.cluster.local:9092"
            - name: GROUP_ID
              value: "order-service-group"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
#infra/k8s/orders-svc.yml

apiVersion: v1
kind: Service
metadata:
  name: orders-svc
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: orders
