apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: muhammedfayiscc/s-cart-payments
          env:
            - name: MONGO_URI
              value: mongodb://payments-mongo-svc:27017/payments
            - name: KAFKA_CLIENT_ID
              value: "payments-service-consumer-1" # You can use unique identifiers per replica if needed
            - name: KAFKA_BROKERS
              value: "kafka-depl-0.kafka-headless.default.svc.cluster.local:9092"
            - name: GROUP_ID
              value: "payments-service-group"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
#infra/k8s/payments-svc.yml

apiVersion: v1
kind: Service
metadata:
  name: payments-svc
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: payments
