export const MINI_LOADER = 'MINI_LOADER';
export const PAGE_LOADER = 'PAGE_LOADER';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const GET_USER_MANAGEMENT_DATA = 'GET_USER_MANAGEMENT_DATA';



